import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

interface ProcurementData {
  company_name?: string
  website?: string
  product_desc?: string
  used_in_nhs?: boolean
  has_data_policy?: boolean
  has_ico_registration?: boolean
  is_dsp_toolkit_compliant?: boolean
}

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 12,
    fontFamily: 'Helvetica',
    lineHeight: 1.5,
  },
  section: {
    marginBottom: 20,
  },
  heading: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 6,
    color: '#007C7A',
  },
  text: {
    fontSize: 12,
    marginBottom: 4,
  },
  footer: {
    marginTop: 30,
    fontSize: 10,
    color: 'gray',
    textAlign: 'center',
  },
})

export default function ProcurementPDF({ data }: { data: ProcurementData }) {
  return (
    <Document>
      <Page style={styles.page}>
        <View style={styles.section}>
          <Text style={[styles.heading, { fontSize: 18 }]}>
            NHS Procurement Readiness Report
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Basic Company Info</Text>
          <Text style={styles.text}>Company Name: {data.company_name || '—'}</Text>
          <Text style={styles.text}>Website: {data.website || '—'}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Product Details</Text>
          <Text style={styles.text}>Product Description: {data.product_desc || '—'}</Text>
          <Text style={styles.text}>Used in NHS Before: {data.used_in_nhs ? 'Yes' : 'No'}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Compliance Checklist</Text>
          <Text style={styles.text}>Data Protection Policy: {data.has_data_policy ? 'Yes' : 'No'}</Text>
          <Text style={styles.text}>ICO Registered: {data.has_ico_registration ? 'Yes' : 'No'}</Text>
          <Text style={styles.text}>
            DSP Toolkit Compliant: {data.is_dsp_toolkit_compliant ? 'Yes' : 'No'}
          </Text>
        </View>

        <Text style={styles.footer}>Generated by Coentry Platform</Text>
      </Page>
    </Document>
  )
}
