// components/pdf/ProcurementPDF.tsx
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  section: {
    marginBottom: 10,
  },
  title: {
    fontSize: 16,
    marginBottom: 10,
    fontWeight: 'bold',
  },
})

type ProcurementData = {
  company_name?: string
  website?: string
  product_desc?: string
  used_in_nhs?: boolean
}

export default function ProcurementPDF({ data }: { data: ProcurementData }) {
  return (
    <Document>
      <Page style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.title}>NHS Procurement Readiness Report</Text>
        </View>

        <View style={styles.section}>
          <Text>Company Name: {data.company_name || '—'}</Text>
          <Text>Website: {data.website || '—'}</Text>
        </View>

        <View style={styles.section}>
          <Text>Product Description:</Text>
          <Text>{data.product_desc || '—'}</Text>
        </View>

        <View style={styles.section}>
          <Text>Used in NHS Before: {data.used_in_nhs ? 'Yes' : 'No'}</Text>
        </View>

        <Text style={{ marginTop: 30, fontSize: 10, color: 'gray' }}>
          Generated by NHS Ready Platform
        </Text>
      </Page>
    </Document>
  )
}
