// lib/docxGenerator.ts
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
} from 'docx'

export async function generateDocxBuffer(data: any): Promise<Blob> {
  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            text: 'NHS Procurement Readiness Report',
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            text: `Company Name: ${data.company_name || '—'}`,
          }),
          new Paragraph({
            text: `Website: ${data.website || '—'}`,
          }),
          new Paragraph({
            text: `Used in NHS: ${data.used_in_nhs ? 'Yes' : 'No'}`,
          }),
          new Paragraph({
            text: 'Product Description:',
            spacing: { after: 80 },
          }),
          new Paragraph({
            text: data.product_desc || '—',
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: '\nGenerated by NHS Ready Platform',
                italics: true,
                size: 18,
              }),
            ],
          }),
        ],
      },
    ],
  })

  const buffer = await Packer.toBlob(doc)
  return buffer
}
