// lib/markdownZipGenerator.ts
import JSZip from 'jszip'

export async function generateMarkdownZip(data: any): Promise<Blob> {
  const zip = new JSZip()

  const mdContent = `# NHS Procurement Readiness Report

## Company Name
${data.company_name || '—'}

## Website
${data.website || '—'}

## Used in NHS
${data.used_in_nhs ? 'Yes' : 'No'}

## Product Description
${data.product_desc || '—'}

---

Generated by NHS Ready.
`

  zip.file('Procurement-Pack.md', mdContent)

  return await zip.generateAsync({ type: 'blob' })
}
