import JSZip from 'jszip'

interface ProcurementData {
  company_name?: string
  website?: string
  product_desc?: string
  used_in_nhs?: boolean
}

export async function generateMarkdownZip(data: ProcurementData): Promise<Blob> {
  const zip = new JSZip()

  const content = `
# NHS Procurement Readiness Report

**Company Name:** ${data.company_name || '—'}
**Website:** ${data.website || '—'}

## Product Description

${data.product_desc || '—'}

## Used in NHS Before

${data.used_in_nhs ? 'Yes' : 'No'}

---

*Generated by NHS Ready Platform*
`

  zip.file('procurement-readiness.md', content.trim())

  const blob = await zip.generateAsync({ type: 'blob' })
  return blob
}
