import JSZip from 'jszip'

interface StepData {
  company_name?: string
  website?: string
  product_desc?: string
  used_in_nhs?: boolean
}

export async function generateMarkdownZip(stepData: StepData): Promise<Blob> {
  const zip = new JSZip()

  const content = `
# NHS Procurement Readiness Report

**Company Name:** ${stepData.company_name || '—'}
**Website:** ${stepData.website || '—'}

## Product Description

${stepData.product_desc || '—'}

## Used in NHS Before?

${stepData.used_in_nhs ? 'Yes' : 'No'}

---

Generated by NHS Ready Platform
`

  zip.file('procurement-report.md', content.trim())

  const blob = await zip.generateAsync({ type: 'blob' })
  return blob
}
